MLSApplication/Models/Sportsman.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MLSApplication.Services;


/*
 * @author: Victor Noe Hernández
 * @version: 1.0.0
 * @description: class for create the players
 */

namespace MLSApplication.Models {

    public class Sportsman {
        //Class parameters
        public static int codeSportsman = 0;

        public int sportsmanId { get; set; }
        
        public String name { get; set; }
        public String lastname { get; set; }
        public double salary { get; set; }
        public String position { get; set; }
        public String futbolTeam { get; set; }
        public String search { get; set; }

        public bool saveSportman(bool structureType){
            try {
                
                codeSportsman++;
                this.sportsmanId = codeSportsman;

                if (structureType){
                    Storage.Instance.listSportman.AddLast(this);
                }else {
                    Storage.Instance.doublylistSportman.pushInList(this);
                }
                
                return true;
            }catch (Exception e) {
                return false;
            }

        }

        public bool deleteSportman(int id, bool structureType){
            if (structureType){
                Storage.Instance.listSportman.Where(c => c.sportsmanId == id).FirstOrDefault();
                return true;
            }else {
                return false;
            }
        }

    }
}

MLSApplication/Controllers/SportsmanController.cs
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomGenerics.Structures;
using MLSApplication.Models;
using MLSApplication.Services;

namespace MLSApplication.Controllers
{
    /*
     * @author: Aylinne Recinos and Victor Hernández
     * @version: 1.0.1
     * @description: controller for the C# list and Doubly Linked List. 
     */

    public class SportsmanController : Controller {
        //Class atributes
        Stopwatch watch = new Stopwatch();
        OperationLog newOperation;
        StreamReader streamReader;

        //Method for selection page
        public ActionResult SelectionPage() {
            return View();
        }

        //Method for selection page
        [HttpPost]
        public ActionResult SelectionPage(Sportsman sportsman, string C_List, string DoublyList){
            try {
                var sportsmanS = Storage.Instance.listSportman;
                if (!string.IsNullOrEmpty(C_List)){
                    Storage.Instance.selectionList = true;
                    return RedirectToAction("Index");
                }
                else if (!string.IsNullOrEmpty(DoublyList)){
                    return RedirectToAction("Index");
                }
                else{
                    return RedirectToAction("Index");
                }
            }catch (Exception){
                return View();
            }
        }

        // GET: Sportsman
        public ViewResult Index(Sportsman model, string sortOrder, string searchString) {
            try{
                var sportsmanDoubly = from r in Storage.Instance.doublylistSportman
                                select r;
                var find = from s in Storage.Instance.listSportman
                               select s;

                watch.Start();
                if (!String.IsNullOrEmpty(searchString)){
                    if (Storage.Instance.selectionList){
                        find = find.Where(s => s.name.Contains(searchString)
                                           || s.lastname.Contains(searchString)
                                           || s.salary.ToString().Contains(searchString) || s.position.Contains(searchString) || s.futbolTeam.Contains(searchString));
                        watch.Stop();
                        addOperation("Find object", "Find object in the LinkedList.", watch.Elapsed.TotalMilliseconds.ToString());
                    }else{
                        sportsmanDoubly = sportsmanDoubly.Where(r => r.name.Contains(searchString)
                                           || r.lastname.Contains(searchString)
                                           || r.salary.ToString().Contains(searchString) || r.position.Contains(searchString) || r.futbolTeam.Contains(searchString));
                        watch.Stop();
                        addOperation("Find object", "Find object in the LinkedList.", watch.Elapsed.TotalMilliseconds.ToString());
                    }
 
                }

                if (Storage.Instance.selectionList){
                    return View(find.ToList());
                }else{
                    return View(sportsmanDoubly.ToList());
                }
            }catch (Exception){
                return View();
            }

        }

        // GET: Sportsman/Details/5
        public ActionResult Details(int id){
            return View();
        }

        // GET: Sportsman/Create
        public ActionResult Create() {
            return View();
        }

        // POST: Sportsman/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection) {
            try {
                var Sportman = new Sportsman {
                    name = collection["name"],
                    lastname = collection["lastname"],
                    salary = int.Parse(collection["salary"]),
                    position = collection["position"],
                    futbolTeam = collection["futbolTeam"],
                };
                watch.Start();
                if (Sportman.saveSportman(Storage.Instance.selectionList)) {
                    watch.Stop();
                    addOperation("New player", "A new player was added", watch.Elapsed.TotalMilliseconds.ToString());
                    return RedirectToAction("Index");
                }else{
                    return View(Sportman);
                }
            }
            catch (Exception){
                return View();
            } 
        }

        // GET: Sportsman/Edit/5
        public ActionResult Edit(int id){
            try {
                if (Storage.Instance.selectionList){
                    var sportman = Storage.Instance.listSportman.Where(c => c.sportsmanId == id).FirstOrDefault();
                    return View(sportman);
                }else{
                    var sportsman = returnObject(id);
                    return View(sportsman);
                }
            }catch {
                return View();
            }
        }

        // POST: Sportsman/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection){
            try{
                var Sportman = new Sportsman {
                    name = collection["name"],
                    lastname = collection["lastname"],
                    salary = int.Parse(collection["salary"]),
                    position = collection["position"],
                    futbolTeam = collection["futbolTeam"],
                };
                
                if (Storage.Instance.selectionList){
                    var sportman = Storage.Instance.listSportman.Where(c => c.sportsmanId == id).FirstOrDefault();
                    watch.Start();
                    Storage.Instance.listSportman.Find(sportman).Value = Sportman;
                    watch.Stop();
                    addOperation("Edit an object", "Edit an object in the LinkedList", watch.Elapsed.TotalMilliseconds.ToString());
                    return RedirectToAction("Index");
                }
                else
                {
                    var sporstman = returnObject(id);
                    Storage.Instance.doublylistSportman.popInList(sporstman);
                    if (Sportman.saveSportman(Storage.Instance.selectionList)){
                        return RedirectToAction("Index");
                    }
                    return RedirectToAction("Index");
                }
            }catch {
                    return RedirectToAction("Index");
            }

        }

        // GET: Sportsman/Delete/5
        public ActionResult Delete(int id){
            var sportman = new Sportsman();
            try {
                if (Storage.Instance.selectionList){
                    if (sportman.deleteSportman(id, Storage.Instance.selectionList)){
                        return View(Storage.Instance.listSportman.Where(c => c.sportsmanId == id).FirstOrDefault());
                    }else{
                        return View();
                    }
                }else{
                    var sportsman = returnObject(id);
                    return View(sportsman);
                }

            }catch {
                return View(sportman);
            }
        }

        //Method for return object by Id
        public Sportsman returnObject(int id){
            var sportsman = new Sportsman();
            DoublyLinkedList<Sportsman> sportmansCopy = Storage.Instance.doublylistSportman;
            while (id != sportsman.sportsmanId) {
                sportsman = sportmansCopy.getObject();
            }
            return sportsman;
        }

        // POST: Sportsman/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection) {
            var sportsman = new Sportsman();
            try {
                if (Storage.Instance.selectionList) {
                    if (sportsman == null) {
                        return View("NotFound");
                    }
                    watch.Start();
                    Storage.Instance.listSportman.Remove(Storage.Instance.listSportman.Where(c => c.sportsmanId == id).FirstOrDefault());
                    watch.Stop();
                    addOperation("Delete an object", "Delete an object in the LinkedList", watch.Elapsed.TotalMilliseconds.ToString());
                    return RedirectToAction("Index");
                }else {
                    sportsman = returnObject(id);
                    watch.Start();
                    Storage.Instance.doublylistSportman.popInList(sportsman);
                    watch.Stop();
                    addOperation("Delete an object", "Delete an object in the Doubly List", watch.Elapsed.TotalMilliseconds.ToString());
                    return RedirectToAction("Index");
                }
            }catch{
                return View(sportsman);
            }
        }

        //Add operation to log document
        public void addOperation(string title, string description, string time) {
            StreamWriter streamWriter = new StreamWriter(AppDomain.CurrentDomain.BaseDirectory + "/Logs/Log-"
            + DateTime.Now.Day+".txt", true);
            newOperation = new OperationLog(title, description, (time + " ms"));
            streamWriter.WriteLine(newOperation.PrintOperation());
            streamWriter.Close();
        }
        
        //Method to load document .csv
        [HttpPost]
        public ActionResult LoadDocument(HttpPostedFileBase file) {
            try {
                Sportsman sportsman = new Sportsman();
                streamReader = new StreamReader(AppDomain.CurrentDomain.BaseDirectory+ "/TestDocuments/" +file.FileName);
                int iteration = 0;
                String data;
                while (streamReader.Peek() >= 0) {
                    String lineReader = streamReader.ReadLine();
                    data = "";

MLSApplication/Views/Sportsman/Create.cshtml
@model MLSApplication.Models.Sportsman

@{
    ViewBag.Title = "Create";
}
    <p></p>
    <h2>
        Create
        <small class="text-muted">portsman</small>
    </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger}" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.salary, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.salary, new { htmlAttributes = new { @class = "form-control", @type = "number"  } })
                @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.futbolTeam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.futbolTeam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.futbolTeam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" onclick="location.href='@Url.Action("Index", "Sportsman")'" class="btn btn-primary">Back to list</button>
</div>

MLSApplication/Views/Sportsman/Delete.cshtml
@model MLSApplication.Models.Sportsman

@{
    ViewBag.Title = "Delete";
}
<br />
<h2>
    Delete
    <small class="text-muted">portsman</small>
</h2>
<hr />
<h2><small class="text-muted">Are you sure you want to delete this?</small></h2>
<div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            Lastname
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastname)
        </dd>

        <dt>
            Salary
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salary)
        </dd>

        <dt>
            Position
        </dt>

        <dd>
            @Html.DisplayFor(model => model.position)
        </dd>

        <dt>
            Futbol Team
        </dt>

        <dd>
            @Html.DisplayFor(model => model.futbolTeam)
        </dd>

    </dl>
    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <button type="button" onclick="location.href='@Url.Action("Index", "Sportsman")'" class="btn btn-primary">Back to list</button>
        </div>
    }
</div>

MLSApplication/Views/Sportsman/Edit.cshtml
@model MLSApplication.Models.Sportsman

@{
    ViewBag.Title = "Edit";
}

    <h2>
        Edit
        <small class="text-muted">portsman</small>
    </h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.sportsmanId)

        <div class="form-group hidden">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                
            </div>

        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastname, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group hidden">
            @Html.LabelFor(model => model.position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.futbolTeam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.futbolTeam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.futbolTeam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" onclick="location.href='@Url.Action("Index", "Sportsman")'" class="btn btn-primary">Back to list</button>
</div>

MLSApplication/Views/Sportsman/Index.cshtml
@model IEnumerable<MLSApplication.Models.Sportsman>

@{
    ViewBag.Title = "SportsMan";
}
<p></p>
<h2>
    Stored records
    <small class="text-muted">(Sportsmans)</small>
</h2>

<hr />
    <div class="agroup-class">
        <button type="button" onclick="location.href='@Url.Action("Create", "Sportsman")'" class="btn btn-primary">Create new</button>
    </div>
    <div class="agroup-class">
        @using (Html.BeginForm())
        {
            <div class="agroup-class">
            <p class="text-info">
                Find: @Html.TextBox("SearchString")
                <input type="submit" value="Search" class="btn btn-default"/>
            </p>
            </div>
        }
    </div>
<br />
<br />

<table class="table">
    <tr>
        <th scope="col">
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th scope="col">
            @Html.DisplayNameFor(model => model.lastname)
        </th>
        <th>
            Salary
        </th>
        <th>
            Position
        </th>
        <th>
            Team
        </th>
        <th>
            Actions
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.futbolTeam)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.sportsmanId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.sportsmanId })
            </td>
        </tr>
    }

</table>
<br />
@using (Html.BeginForm("LoadDocument", "Sportsman", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <hr />
    <h4 class="text-info">Load records from file</h4>
    <div class="agroup-class">
        <input type="file" name="file" accept=".csv" />
    </div>
    <div class="agroup-class">
        <input type="submit" value="Load file" class="btn btn-default" />
    </div>
}

MLSApplication/Views/Sportsman/SelectionPage.cshtml
@model MLSApplication.Models.Sportsman

@{
    ViewBag.Title = "SelectionPage";
}

<div style="width:100%;text-align:center; " class="jumbotron">
    <h1>MLS Application</h1>
    <p class="lead">Select the type of list do you prefer to use.</p>
    <hr class="my-4">
</div>


@using (Html.BeginForm("SelectionPage", "Sportsman", FormMethod.Post))
{
    <br />
    <div class="agroup-class">
        <input type="submit" name="C_List" value="C_List" class="btn btn-default btn-lg btn-block" />
    </div>
        <div class="agroup-class">
            <input type="submit" name="DoublyList" value="DoublyList" class="btn btn-default btn-lg btn-block" />
        </div>
        }